# Generated by Django 5.0 on 2024-01-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='role_id',
            new_name='role',
        ),
    ]
