# Generated by Django 4.2.6 on 2024-01-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_animals_real_name_alter_animals_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='real_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='real_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=20),
        ),
    ]
