# Generated by Django 4.2.6 on 2024-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_roles_real_name_alter_animals_real_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50, null=True)),
                ('how_know', models.CharField(max_length=20, null=True)),
                ('form', models.CharField(max_length=20, null=True)),
                ('answer', models.ManyToManyField(to='account.question')),
            ],
        ),
    ]
